### ISSUE TITLE
Pagination is wrong

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/LimeBootstrapAppStoreSite#11]
Three pages are shown even though there only is two.

**Comment by justFredster** [comment]
Now even more pages are shown even though there are only 2.

Also need to check behavior when searching.

**Comment by burnroth** [comment]
The pages are generated from the json file that is passed from the API to the pageFactory() method. 
At the bottom of this file, there is an object stating that there are 6 total pages,
`"_self": { "_total_pages": 6, "_current_page": 1 }`
 and thats why we get a couple of empty pages.

I could probably hack around this, but i think it would be better to fix the information in the json file, if that is possible :) 

@justFredster

**Comment by justFredster** [comment]
@LarsCJensen this sounds like a bug in the LBS Service, right?

**Comment by justFredster** [comment]
@LarsCJensen Seems like the pagination is based on the total number of rows in the `addon` table (currently 68 meaning 8 pages with 9 items per page) instead of the number of rows where `show_in_store = true` which it should be.

**Comment by LarsCJensen** [comment]
Yes, it is using the wrong variable when it calculates that. I will fix it during the summer

**Comment by LarsCJensen** [comment]
I have fixed it in https://github.com/Lundalogik/LimeBootstrapServices
