### ISSUE TITLE
Add button "contact us"

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrapAppStoreSite#20]
Clicking the button should redirect to https://lime-crm.se/kontakta-oss/.

In other words: Similar to the button that is on lime-crm.com, as shown below:

![image](https://user-images.githubusercontent.com/5981735/58332519-b2d53c00-7e3b-11e9-8ee9-4cf5dfd0d37f.png)

**Comment by justFredster** [comment]
@jennieeverhed Is this something that can be included in your work?

**Comment by jennieeverhed** [comment]
Yes! We thought it would be a good idea to be able to contact us if you get confused. :)

**Comment by justFredster** [comment]
Fixed!
