### ISSUE TITLE
Remove the image array from each addons object

### ISSUE THREAD

**Issue by burnroth** [Lundalogik/LimeBootstrapAppStoreSite#22]
To speed up page load

**Comment by justFredster** [comment]
Which consequences will this have to the visitor of the Lime Store site? @burnroth @LarsCJensen

**Comment by burnroth** [comment]
The initial load will be much faster :) 

Each addon contains an array with images that we dont even use. And some addons contain like 150 images @justFredster

**Comment by justFredster** [comment]
@burnroth Ok, something is wrong then. Shouldn't be 150 images! :)

The thought is that there could be a few images that would be presented in a carousel. That was never implemented in the HTML though. Once it is, maybe loading the images for a specific add-on when you click it to open it would be possible?

**Comment by justFredster** [comment]
As long as we don't remove the actual image shown when you open the modal for a specific add-on. :)
