### ISSUE TITLE
Multiple images should be able to be shown in the store

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/LimeBootstrapAppStoreSite#5]
Right now only one image per addon is shown.

**Comment by justFredster** [comment]
We wait with this one.

**Comment by burnroth** [comment]
@LarsCJensen  Is it possible to remove the "images" array in each "addon" object from the API? All the images are causing the page to load forever, and the load time increases significantly for each addon we are publishing.

**Comment by LarsCJensen** [comment]
Yes, could you add a separate issue for this @burnroth?

**Comment by burnroth** [comment]
@LarsCJensen for shizzle
